-- 코드를 입력하세요
SELECT
    O.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM (SELECT * FROM FOOD_ORDER WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31') O
    INNER JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID