-- 코드를 입력하세요
SELECT
    DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE 
    MONTH(H.START_DATE) = 10 AND 
    C.CAR_TYPE = '세단'
ORDER BY 1 DESC