-- 코드를 입력하세요
SELECT
    CATEGORY,
    PRICE,
    PRODUCT_NAME
FROM (
    SELECT
        CATEGORY,
        PRICE,
        PRODUCT_NAME,
        ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM FOOD_PRODUCT
) RANKED_TBL
WHERE PRICE_RANK = 1 AND
    CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC
