-- 코드를 입력하세요
SELECT
    U.USER_ID,
    U.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD G
    LEFT JOIN USED_GOODS_USER U ON G.WRITER_ID = U.USER_ID
WHERE G.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3